In [1]:
import sqlalchemy as db
from getpass import getpass

In [2]:
password = getpass("Mysql Password: ")

Mysql Password: ········

In [3]:
dbName = "lab - MySQL Select"
connectionData = f"mysql+pymysql://root:{password}@localhost/{dbName}"

In [4]:
engine = db.create_engine(connectionData)
print("Connected to server!")

Connected to server!

In [5]:
import pandas as pd

In [16]:
step_1 = pd.read_sql_query("""
SELECT 
	t.title_id, au.au_id, (t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100 AS Royalty
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
""", engine)

In [20]:
step_1

    title_id        au_id   Royalty
0     PS3333  172-32-1176  0.002998
1     PS3333  172-32-1176  0.002998
2     PS3333  172-32-1176  0.002998
3     PS3333  172-32-1176  0.002998
4     BU1032  213-46-8915  0.002499
5     BU1032  213-46-8915  0.002499
6     BU1032  213-46-8915  0.004998
7     BU1032  213-46-8915  0.004998
8     BU2075  213-46-8915  0.002512
9     BU2075  213-46-8915  0.002512
10    BU2075  213-46-8915  0.002512
11    BU2075  213-46-8915  0.002512
12    BU2075  213-46-8915  0.002512
13    BU2075  213-46-8915  0.002512
14    BU2075  213-46-8915  0.002512
15    BU2075  213-46-8915  0.002512
16    PC1035  238-95-7766  0.011016
17    PC1035  238-95-7766  0.011016
18    PC1035  238-95-7766  0.011016
19    PC1035  238-95-7766  0.011016
20    PC1035  238-95-7766  0.011016
21    BU1111  267-41-2394  0.007469
22    BU1111  267-41-2394  0.007469
23    BU1111  267-41-2394  0.007469
24    BU1111  267-41-2394  0.007469
25    BU1111  267-41-2394  0.007469
26    BU1111  267-41-2394  0.007469
27    BU1111  267-41-2394  0.007469
28    BU1111  267-41-2394  0.007469
29    TC7777  267-41-2394  0.009993
..       ...          ...       ...
142   PS2091  899-46-2035  0.019710
143   PS2091  899-46-2035  0.019710
144   PS2091  899-46-2035  0.002628
145   PS2091  899-46-2035  0.002628
146   PS2091  899-46-2035  0.002628
147   PS2091  899-46-2035  0.002628
148   PS2091  899-46-2035  0.005256
149   PS2091  899-46-2035  0.005256
150   PS2091  899-46-2035  0.005256
151   PS2091  899-46-2035  0.005256
152   PS2091  998-72-3567  0.000788
153   PS2091  998-72-3567  0.000788
154   PS2091  998-72-3567  0.000788
155   PS2091  998-72-3567  0.000788
156   PS2091  998-72-3567  0.019710
157   PS2091  998-72-3567  0.019710
158   PS2091  998-72-3567  0.019710
159   PS2091  998-72-3567  0.019710
160   PS2091  998-72-3567  0.002628
161   PS2091  998-72-3567  0.002628
162   PS2091  998-72-3567  0.002628
163   PS2091  998-72-3567  0.002628
164   PS2091  998-72-3567  0.005256
165   PS2091  998-72-3567  0.005256
166   PS2091  998-72-3567  0.005256
167   PS2091  998-72-3567  0.005256
168   PS2106  998-72-3567  0.001750
169   PS2106  998-72-3567  0.001750
170   PS2106  998-72-3567  0.001750
171   PS2106  998-72-3567  0.001750

[172 rows x 3 columns]

In [19]:
temp_table = pd.read_sql_query("""
CREATE TEMPORARY TABLE results(
SELECT 
	t.title_id, au.au_id, (t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100 AS Royalty
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
);
""", engine)

InternalError: (pymysql.err.InternalError) (1050, "Table 'results' already exists")
[SQL:
CREATE TEMPORARY TABLE results(
SELECT
	t.title_id, au.au_id, (t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100 AS Royalty
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
);
]
(Background on this error at: http://sqlalche.me/e/2j85)

In [26]:
step_2 = pd.read_sql_query("""
SELECT 
	t.title_id, au.au_id, sum((t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100) AS Total
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
	GROUP BY t.title_id, au.au_id
	ORDER BY t.title_id DESC
""", engine)

In [27]:
step_2 

#He intentado crear una temporary table, pero como mirar en el ej.anterior no he conseguido. 
#Tan poco supe utilizar subqueries.

   title_id        au_id     Total
0    TC7777  267-41-2394  0.029980
1    TC7777  472-27-2349  0.029980
2    TC7777  672-71-3249  0.022485
3    TC4203  648-92-1872  0.023422
4    TC3218  807-91-6654  0.067040
5    PS7777  486-29-1786  0.003995
6    PS3333  172-32-1176  0.011994
7    PS2106  998-72-3567  0.007000
8    PS2091  899-46-2035  0.113530
9    PS2091  998-72-3567  0.113530
10   PS1372  724-80-9391  0.086360
11   PS1372  756-30-7391  0.028787
12   PC9999  486-29-1786       NaN
13   PC8888  427-17-2319  0.080000
14   PC8888  846-92-7186  0.080000
15   PC1035  238-95-7766  0.055080
16   MC3021  722-51-5454  0.030618
17   MC3021  899-46-2035  0.091853
18   MC2222  712-45-1867  0.014393
19   BU7832  274-80-9391  0.023988
20   BU2075  213-46-8915  0.020093
21   BU1111  267-41-2394  0.059750
22   BU1111  724-80-9391  0.039833
23   BU1032  213-46-8915  0.014993
24   BU1032  409-56-7008  0.009995
25     None  341-22-1782       NaN
26     None  527-72-3246       NaN
27     None  724-08-9931       NaN
28     None  893-72-1158       NaN

In [38]:
#Intento por subqueries:

step_3 = pd.read_sql_query("""
SELECT 
	au.au_id, sum(Total)
	FROM authors as au
	WHERE au.au_id IN (
SELECT 
	t.title_id, au.au_id, sum((t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100) AS Total
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
	GROUP BY t.title_id, au.au_id
	ORDER BY t.title_id DESC
)
	ORDER BY t.title_id DESC
	limit 3
""", engine)

InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'Total' in 'field list'")
[SQL:
SELECT
	au.au_id, sum(Total)
	FROM authors as au
	WHERE au.au_id IN (
SELECT
	t.title_id, au.au_id, sum((t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100) AS Total
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
	GROUP BY t.title_id, au.au_id
	ORDER BY t.title_id DESC
)
	ORDER BY t.title_id DESC
	limit 3
]
(Background on this error at: http://sqlalche.me/e/2j85)

In [39]:
step_3 = pd.read_sql_query("""
SELECT au.au_id, sum(Total)
	FROM (
SELECT 
	t.title_id, au.au_id, sum((t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100) AS Total
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
	GROUP BY t.title_id, au.au_id
	ORDER BY t.title_id DESC
) AS results_2
	ORDER BY t.title_id DESC
	Limit 3
""", engine)

InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'au.au_id' in 'field list'")
[SQL:
SELECT au.au_id, sum(Total)
	FROM (
SELECT
	t.title_id, au.au_id, sum((t.price*sl.qty*t.royalty)/(100*tta.royaltyper)/100) AS Total
	FROM authors as au
	LEFT JOIN titleauthor as tta ON au.au_id = tta.au_id
	LEFT JOIN titles as t ON tta.title_id = t.title_id
	LEFT JOIN sales as sl ON t.title_id = sl.title_id
	LEFT JOIN roysched as ro ON sl.title_id = ro.title_id
	GROUP BY t.title_id, au.au_id
	ORDER BY t.title_id DESC
) AS results_2
	ORDER BY t.title_id DESC
	Limit 3
]
(Background on this error at: http://sqlalche.me/e/2j85)